In [1]:
import pandas as pd
import matplotlib.pyplot as plt


from connect import connection_string
connection_string

'mysql+pymysql://root:TumyetO7@127.0.0.1:3306/liane_library'

In [30]:
# Define the SQL query as a string
query_books = "SELECT * FROM books WHERE Author = 'Niels Zimmermann';"

# Send the query to the database and store results in a DataFrame
books_df = pd.read_sql(query_books, con=connection_string)

# Display results
books_df.head()

,BookID,Title,Author,Isbn
0,10010,Advanced Plant Nutrition and Fertilizers,Niels Zimmermann,978-1-74531-713-4
1,10011,Skateboarding: Mastering Lifestyle on Board,Niels Zimmermann,978-0-14-274848-0
2,10012,Rocket Science and boosting Mechanics,Niels Zimmermann,978-0-00-880035-2

In [31]:
query_active_loans = """
    SELECT 
        borrowers.FirstName, 
        borrowers.LastName, 
        books.Title, 
        loans.BorrowDate
    FROM loans
    JOIN borrowers ON loans.BorrowerID = borrowers.BorrowerID
    JOIN books ON loans.BookID = books.BookID;
"""

loans_df = pd.read_sql(query_active_loans, con=connection_string)
loans_df

      FirstName LastName                                    Title  BorrowDate
0         Laura   Reeves  Enterprise-Wide Incremental Open System  2014-06-29
1         Laura   Reeves            Inverse Asynchronous Approach  2006-02-24
2         Laura   Reeves                Extended Bottom-Line Core  2022-04-06
3         Laura   Reeves  Assimilated Upward-Trending Parallelism  2025-09-21
4         Laura   Reeves         Exclusive Web-Enabled Capability  2018-09-10
...         ...      ...                                      ...         ...
24995      Tina   Nelson          Focused 6Thgeneration Algorithm  2008-03-05
24996      Tina   Nelson        Ameliorated Analyzing Application  2019-02-17
24997      Tina   Nelson                  Ameliorated Exuding Hub  2001-07-03
24998      Tina   Nelson           Face-To-Face Global Complexity  2008-05-10
24999      Tina   Nelson       Mandatory Heuristic Superstructure  2011-03-18

[25000 rows x 4 columns]

In [32]:
# Update module: Change a book title with an explicit commit


from sqlalchemy import create_engine, text

# Create an engine to connect to the database
engine = create_engine(connection_string)

# Define the update query
update_query = """
    UPDATE Books
    SET Title = "Skateboarding! Mastering Lifestyle on Board"
    WHERE BookId = 10011;
"""

# Execute the update query with an explicit commit
with engine.connect() as connection:
    transaction = connection.begin()
    try:
        connection.execute(text(update_query))
        transaction.commit()
    except:
        transaction.rollback()
        raise

In [33]:
from sqlalchemy import create_engine, text

# Create an engine to connect to the database
engine = create_engine(connection_string)

# Define the update query
update_query = """
    
"""

# Execute the update query with an explicit commit
with engine.connect() as connection:
    transaction = connection.begin()
    try:
        connection.execute(text(update_query))
        transaction.commit()
    except:
        transaction.rollback()
        raise

OperationalError: (pymysql.err.OperationalError) (1065, 'Query was empty')
[SQL:

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
pd.read_sql("""
            SELECT *
            FROM Books
            WHERE BookId = 10011;
            """,
            con = connection_string)

,BookID,Title,Author,Isbn
0,10011,Skateboarding! Mastering Lifestyle on Board,Niels Zimmermann,978-0-14-274848-0

In [ ]:
  # Bsp Datenbankabruf mit Pandas
    try:
        query = "SELECT Title, Author, Genre, Isbn FROM books"
        df_books = pd.read_sql(query, con=engine)
        
        if not df_books.empty:
            st.dataframe(df_books, use_container_width=True, hide_index=True)
        else:
            st.warning("Die Bibliothek ist noch leer. Liane muss erst Bücher hinzufügen!")
    except Exception as e:
        st.error(f"Fehler bei der Datenbankverbindung: {e}")

In [ ]:
import streamlit as st

# Title
st.title("Streamlit Demo")

In [ ]:
OPEN_LIBRARY_URL = "https://openlibrary.org"

def get_cover_url(isbn: str, size: str = "M") -> str:
    return f"https://covers.openlibrary.org/b/isbn/{isbn}-{size}.jpg"

In [ ]:
from db import get_engine
engine = get_engine)
def create_book(title, author_id, genre_id, isn, published_at, rating):
with engine.connect() as conn:
conn.execute(text("""
INSERT INTO books (title, author_id, genre_id, isn, published_at, rating)
VALUES (:title, :author_id, :genre_id, isbn, published_at, rating)
"#"），｛
"title": title,
"author_id": author_id,
"genre_id": genre_id,
"isbn": isbn,
"published_at": published_at,
"rating": rating
I
})
conn.commit(
def delete_book(book_id): 2 usages & Marvin Atorf
with engine.connect() as conn:
conn. execute(text("DELETE FROM books WHERE book_id = :id"), f"id": book_idł)