In [ ]:
import pandas as pd
import matplotlib.pyplot as plt


from connect import connection_string

'mysql+pymysql://root:TumyetO7@127.0.0.1:3306/liane_library'

In [6]:
# Die SQL-Abfrage als String definieren
query_books = "SELECT * FROM books WHERE Author = 'Niels Zimmermann';"

# Die Abfrage an die Datenbank senden und als DataFrame speichern
books_df = pd.read_sql(query_books, con=connection_string)

# Ergebnis anzeigen
books_df.head()

,BookID,Title,Author,Isbn
0,10010,Advanced Plant Nutrition and Fertilizers,Niels Zimmermann,978-1-74531-713-4
1,10011,Skateboarding: Mastering Lifestyle on Board,Niels Zimmermann,978-0-14-274848-0
2,10012,Rocket Science and boosting Mechanics,Niels Zimmermann,978-0-00-880035-2

In [7]:
query_active_loans = """
    SELECT 
        borrowers.FirstName, 
        borrowers.LastName, 
        books.Title, 
        loans.BorrowDate
    FROM loans
    JOIN borrowers ON loans.BorrowerID = borrowers.BorrowerID
    JOIN books ON loans.BookID = books.BookID;
"""

loans_df = pd.read_sql(query_active_loans, con=connection_string)
loans_df

      FirstName LastName                                    Title  BorrowDate
0         Laura   Reeves  Enterprise-Wide Incremental Open System  2014-06-29
1         Laura   Reeves            Inverse Asynchronous Approach  2006-02-24
2         Laura   Reeves                Extended Bottom-Line Core  2022-04-06
3         Laura   Reeves  Assimilated Upward-Trending Parallelism  2025-09-21
4         Laura   Reeves         Exclusive Web-Enabled Capability  2018-09-10
...         ...      ...                                      ...         ...
24995      Tina   Nelson          Focused 6Thgeneration Algorithm  2008-03-05
24996      Tina   Nelson        Ameliorated Analyzing Application  2019-02-17
24997      Tina   Nelson                  Ameliorated Exuding Hub  2001-07-03
24998      Tina   Nelson           Face-To-Face Global Complexity  2008-05-10
24999      Tina   Nelson       Mandatory Heuristic Superstructure  2011-03-18

[25000 rows x 4 columns]